### ISSUE TITLE
Wrong download link on draculatheme.com

### ISSUE THREAD

**Issue by svensto190** [scottzach1/dracula-theme-eclipse#1]
Hey, the download link for the eclipse theme on your website is pointing to the wrong repository (https://draculatheme.com/eclipse). 
It's : https://github.com/dracula/dracula/archive/master.zip
It should be : https://github.com/dracula/eclipse/archive/master.zip

**Comment by scottzach1** [comment]
Hey @svensto190, great spot! Thanks for pointing that out :), 

I have corrected the link within the repo. I am unsure how long this may take to apply at [draculatheme.com/eclipse](https://draculatheme.com/eclipse).

I'll leave this issue open until I see the link has updated on the site. (Feel free to close if it has updated for you). 

Cheers Z.
