### ISSUE TITLE
Drakula Eclipse in Windows (Top Bars)

### ISSUE THREAD

**Issue by drakgoku** [scottzach1/dracula-theme-eclipse#4]
How in Windows can you have the same theme in the IDE as in the image?
Current Windows
![image](https://user-images.githubusercontent.com/2928888/113801032-5261f600-9758-11eb-866f-4495e84317f9.png)
draculatheme
![image](https://raw.githubusercontent.com/dracula/eclipse/master/configuration.png)

In draculatheme the IDE seems much cleaner with the hidden bars (or the same color as the background), the more attractive checkboxes or even everything cleaner. How can it be done?

**Comment by zenorocha** [comment]
@scottzach1 can you take a look?

**Comment by scottzach1** [comment]
Hey @drakgoku, your question appears to overlap with #2, which I just replied to, so I will copy my response here.

> Unfortunately, the taskbar cannot be changed by Eclipse as they natively use the default system title bars to the best of my knowledge. In the provided screenshots, these title bars are using Dracula colours as they are taken on a system running Linux where [GTK](https://www.gtk.org/docs/) has additionally been themed using [dracula/gtk](https://draculatheme.com/gtk). A little searching online yielded the following unofficial Dracula theme for Windows system title bars. I do not know of the developer or software, so I cannot comment on whether it is working / safe.
>
> <https://www.deviantart.com/niivu/art/Dracula-for-Windows-10-843182521>

Sorry, I don't have any easy answer to your question. I would love to hear how you get on if you decide to take this further!

Best of luck :smile:

(edit: formatting on phone)

**Comment by drakgoku** [comment]
Good news. I've only done 2 things. It is a much prettier arrangement than before, it is not 100% what I am looking for, but it is a great help.
1 - Copy Drakula's aero in windows resources
2 - Install UltraUXThemePatcher

![image](https://user-images.githubusercontent.com/2928888/113893871-b8399680-97c7-11eb-82f2-ec7665dee697.png)
I haven't installed anything else and it really changed the windows GUI.
![image](https://user-images.githubusercontent.com/2928888/113893960-d606fb80-97c7-11eb-82e9-eff9edee8ec0.png)

**Comment by scottzach1** [comment]
Awesome work! Thanks for sharing that looks super tidy 😋.

Unfortunately I think this extends beyond the scope of this project. Feel free to close the issue if you feel it has been resolved.

Cheers!
