### ISSUE TITLE
Eclipse - Java attribute incorrect color

### ISSUE THREAD

**Issue by drakgoku** [scottzach1/dracula-theme-eclipse#5]
The color of the Eclipse attribute does not seem correct with what is shown in the preview.
![image](https://user-images.githubusercontent.com/2928888/113896425-34cd7480-97ca-11eb-8906-fd6d91e38fb6.png)

Are there any color updates or something you don't know about?

By the way, in Visual Studio Code, it's a bit more beautiful and stylish.
![image](https://user-images.githubusercontent.com/2928888/113896885-a4436400-97ca-11eb-8526-93e6a9549261.png)

**Comment by drakgoku** [comment]
Hello, sorry, I did not understand you.
Could the same style and color as VSC be passed to eclipse?

**Comment by drakgoku** [comment]
Could the same style and color as VSC be passed to eclipse ?, because is it very stylish.

I would also like to comment that when you select a folder, project, file ... there is nothing "outline" that tells you.
![image](https://user-images.githubusercontent.com/2928888/114120380-a867a280-98ec-11eb-9e21-f3c24a9a60b2.png)
For example:
![image](https://user-images.githubusercontent.com/2928888/114120414-bd443600-98ec-11eb-993e-ad9ebe3290b9.png)

**Comment by drakgoku** [comment]
hey!, do you know anything about this that I mentioned? I hope it does not fall into oblivion.

**Comment by scottzach1** [comment]
Hey @drakgoku,

Regarding your first screenshot, it appears that there may be a bug. This is likely with the Darkest Dark plugin, as the preview shows the intended colours. Apologies, I haven't gotten around to looking into it. Life has been pretty busy, and I haven't had to touch Java in over a year. I will attempt to look into this at some point next week; alternatively, feel free to submit a pull request if you notice a problem with the [dracula-theme.xml](https://raw.githubusercontent.com/dracula/eclipse/master/dracula-theme.xml) file.

In response to the discrepancies between the Eclipse theme and the VS Code one. From memory, this theme was mainly inspired by my personal favourite Dracula implementation; the [Material UI > Dracula](https://github.com/ChrisRM/material-theme-jetbrains) theme for IntelliJ, using the [dracula-theme](https://github.com/dracula/dracula-theme) colour palette. Unfortunately, when creating this theme, I was limited by how few attributes the Eclipe Darkest Dark XML template allowed me to theme.

To the best of my knowledge, you cannot import VS Code theme files into Eclipse natively. I am unaware of any converters that exist either. You might be able to create a theme that better suits your needs using this [eclipsecolorthemes](http://www.eclipsecolorthemes.org/?view=theme&id=48678) resource.

This is likely an against the grain suggestion, but unless you are using Java-SE or have string requirements for Eclipse (perhaps studies?), IntelliJ Community is free and open-source. It would be my highest recommended Java IDE.

Best of luck if you decide to try any of these options, and sorry again, I don't have any straightforward solutions.

**Comment by drakgoku** [comment]
If the interest that is put is 0. Then why not close the publication?

It doesn't make sense to have an open post, it seems like it's open for people to come in and think "hey this is still working", when in fact this is "dead"

Shut up... if I hadn't replied to this message... it would still be open from 7Apr/22 until 23, 24... or who knows.

Please close the post... stop wasting our time checking for updates
