### ISSUE TITLE
Can the dracula team make a nice Eclipse theme?

### ISSUE THREAD

**Issue by drakgoku** [scottzach1/dracula-theme-eclipse#9]
All Java users are looking for the acclaimed photo:
![image](https://user-images.githubusercontent.com/2928888/163348476-73f9a7c7-dc7c-4218-bd78-f256c8db8c49.png)

Obviously everyone has seen this post "https://github.com/dracula/eclipse/issues/4"

I answer you. Java programmers actually use Eclipse. The problem with eclipse is that it has a very tired design, they seem to be from the 39's, from the second world war.
With the dracula theme this changes a bit.

Some daring few go to Intellij idea because in this aspect (about the design) it is more customizable and has a better theme and is cleaner. But Intellij has 100 times more problems.
https://intellij-support.jetbrains.com/hc/en-us/community/posts/5106558224274-60-sec-to-create-a-primitive-project-with-ERROR

Since Eclipse has a poor design it reminds me of this "blurred image": When I see it..."

![image](https://user-images.githubusercontent.com/2928888/163349465-a3841423-24fc-4a16-92bd-973f5b464cbb.png)

We want something fresh like:

![image](https://user-images.githubusercontent.com/2928888/163350214-31e860d2-a64d-497f-9a75-366d59c16f09.png)

The problem is that Eclipse's user interface is very tied to the operating system. (80 year old Eclipse programmers/employees can't see the problem)

So is there anything the dracula team can do about it?
Can the Dracula team make a good Eclipse theme? without having to depend on external programs?

It would be the salvation of many people.

Intellij ... every day I hear more hoaxes that it is the best IDE... I don't want to hear more hoaxes.

_I hope that the heads of the Dracula project and team don't use Intellij... if not... then we'll be left without a theme for Eclipse much to my chagrin._

_This reminds me of all the WoW players trying to escape from their own game to find a new MMORPG. Same thing with Eclipse, trying to escape..._

_The same story always repeats itself._

This was also posted for Eclipse
https://www.eclipse.org/forums/index.php/t/1110589/

**Comment by johanjah** [comment]
I'm eclipse users from the begining. Currently moving to Intelij, not because of the appearance/themes. but because of the easiness and functionality.

check now, the current eclipse (202203) can't comment the simple pom xml.

**Comment by drakgoku** [comment]
If the interest that is put is 0. Then why not close the publication?

It doesn't make sense to have an open post, it seems like it's open for people to come in and think "hey this is still working", when in fact this is "dead"

Shut up... if I hadn't replied to this message... it would still be open from 14 Apr/22 until 23, 24... or who knows.

Close the post... stop wasting our time.
